import React from 'react';
import { Camera, Heart, Users, Briefcase, Star, Plus } from 'lucide-react';

export const categories = [
  { id: 'WeddingGroom', name: 'Wedding (Groom)', icon: <Heart className="w-5 h-5" /> },
  { id: 'WeddingBride', name: 'Wedding (Bride)', icon: <Heart className="w-5 h-5" /> },
  { id: 'WeddingBoth', name: 'Wedding (Both)', icon: <Heart className="w-5 h-5" /> },
  { id: 'Birthday', name: 'Birthday / Rice', icon: <Star className="w-5 h-5" /> },
  { id: 'Upanayan', name: 'Upanayan', icon: <Users className="w-5 h-5" /> },
  { id: 'PrePostWedding', name: 'Pre/Post Wedding', icon: <Camera className="w-5 h-5" /> },
  { id: 'ShortFilm', name: 'Short Film / YT', icon: <Briefcase className="w-5 h-5" /> },
  { id: 'Event', name: 'Event', icon: <Users className="w-5 h-5" /> },
  { id: 'ModelShoot', name: 'Model Shoot', icon: <Camera className="w-5 h-5" /> },
  { id: 'AddOn', name: 'Add-Ons', icon: <Plus className="w-5 h-5" /> },
];

export const packageData: Record<string, any[]> = {
  'WeddingGroom': [
    {
      name: 'Silver Package (Crop Sensor)',
      price: 30000,
      description: '(3+1 days) 1 Photographer, 1 Videographer',
      features: [
        'Pre wedding photo',
        'Pre wedding video',
        '20 Sheets wedding album (basic)',
        'Wedding teaser',
        'Ritual wise full video (30-40min)',
        'All Raw backup',
        'Retouch photography',
        'E-invitation'
      ],
      btnColor: 'bg-gray-900 hover:bg-black',
    },
    {
      name: 'Gold Package (Full Sensor)',
      price: 45000,
      description: '(3+1 days) 1 Photographer, 1 Videographer',
      popular: true,
      features: [
        'Candid photography',
        'Pre wedding photo',
        'Pre wedding video',
        '20 Sheets wedding album Standard',
        'Wedding teaser',
        'Ritual wise full video (30-40min)',
        'All Raw backup',
        'Retouch photography',
        'Interview of family and friend',
        'E-invitation',
        'Vlog & reels',
        'Drone (1 day)'
      ],
      btnColor: 'bg-yellow-600 hover:bg-yellow-700',
    },
    {
      name: 'Diamond Package (Full Sensor)',
      price: 120000,
      description: '(3+1 days) 2 Photographers, 1 Videographer',
      features: [
        'Candid photography',
        'Pre wedding photo',
        'Pre wedding video',
        '20 Sheets wedding album premium',
        'Wedding teaser',
        'Ritual wise full video (30-40min)',
        'All Raw backup',
        'Retouch photography',
        'Interview of family and friend',
        'E-invitation',
        'Vlog & reels',
        '1 Guest photographer',
        'Guest photo instant delivery',
        '15 days complete delivery',
        'Drone full event'
      ],
      btnColor: 'bg-blue-900 hover:bg-blue-950',
    }
  ],
  'WeddingBride': [
    {
      name: 'Silver Package (Crop Sensor)',
      price: 28000,
      description: '(2+1 days) 1 Photographer, 1 Videographer',
      features: [
        'Pre wedding photo',
        'Pre wedding video',
        '20 Sheets wedding album (basic)',
        'Wedding teaser',
        'Ritual wise full video (30-40min)',
        'All Raw backup',
        'Retouch photography',
        'E-invitation'
      ],
      btnColor: 'bg-gray-900 hover:bg-black',
    },
    {
      name: 'Gold Package (Full Sensor)',
      price: 40000,
      description: '(2+1 days) 1 Photographer, 1 Videographer',
      popular: true,
      features: [
        'Candid photography',
        'Pre wedding photo',
        'Pre wedding video',
        '20 Sheets wedding album Standard',
        'Wedding teaser',
        'Ritual wise full video (30-40min)',
        'All Raw backup',
        'Retouch photography',
        'Interview of family and friend',
        'E-invitation',
        'Vlog & reels',
        'Drone (1 day)'
      ],
      btnColor: 'bg-yellow-600 hover:bg-yellow-700',
    },
    {
      name: 'Diamond Package (Full Sensor)',
      price: 100000,
      description: '(2+1 days) 2 Photographers, 1 Videographer',
      features: [
        'Candid photography',
        'Pre wedding photo',
        'Pre wedding video',
        '20 Sheets wedding album premium',
        'Wedding teaser',
        'Ritual wise full video (30-40min)',
        'All Raw backup',
        'Retouch photography',
        'Interview of family and friend',
        'E-invitation',
        'Vlog & reels',
        '1 Guest photographer',
        'Guest photo instant delivery',
        '15 days complete delivery',
        'Drone full event'
      ],
      btnColor: 'bg-blue-900 hover:bg-blue-950',
    }
  ],
  'WeddingBoth': [
    {
      name: 'Silver Package (Crop Sensor)',
      price: 50000,
      description: '(3+1 days) 1 Photographer, 1 Videographer',
      features: [
        'Pre wedding photo',
        'Pre wedding video',
        '20 Sheets wedding album (basic)',
        'Wedding teaser',
        'Ritual wise full video (30-40min)',
        'All Raw backup',
        'Retouch photography',
        'E-invitation'
      ],
      btnColor: 'bg-gray-900 hover:bg-black',
    },
    {
      name: 'Gold Package (Full Sensor)',
      price: 75000,
      description: '(3+1 days) 1 Photographer, 1 Videographer',
      popular: true,
      features: [
        'Candid photography',
        'Pre wedding photo',
        'Pre wedding video',
        '20 Sheets wedding album Standard',
        'Wedding teaser',
        'Ritual wise full video (30-40min)',
        'All Raw backup',
        'Retouch photography',
        'Interview of family and friend',
        'E-invitation',
        'Vlog & reels',
        'Drone (1 day)'
      ],
      btnColor: 'bg-yellow-600 hover:bg-yellow-700',
    },
    {
      name: 'Diamond Package (Full Sensor)',
      price: 220000,
      description: '(3+1 days) 1 Photographer, 1 Videographer',
      features: [
        'Candid photography',
        'Pre wedding photo',
        'Pre wedding video',
        '20 Sheets wedding album premium',
        'Wedding teaser',
        'Ritual wise full video (30-40min)',
        'All Raw backup',
        'Retouch photography',
        'Interview of family and friend',
        'E-invitation',
        'Vlog & reels',
        '1 Guest photographer',
        'Guest photo instant delivery',
        '15 days complete delivery',
        'Drone full event'
      ],
      btnColor: 'bg-blue-900 hover:bg-blue-950',
    }
  ],
  'Birthday': [
    {
      name: 'Silver Package (Crop Sensor)',
      price: 10000,
      description: '(1 day) 1 Photographer, 1 Videographer',
      features: [
        '15 Sheets wedding album',
        'Ritual wise full video (10-20min)',
        'All Raw backup',
        'Retouch photography',
        'E-invitation'
      ],
      btnColor: 'bg-gray-900 hover:bg-black',
    },
    {
      name: 'Gold Package (Full Sensor)',
      price: 15000,
      description: '(1 day) 1 Photographer, 1 Videographer',
      popular: true,
      features: [
        'Portrait photography',
        '20 Sheets wedding album',
        'Ritual wise full video (10-20min)',
        'All Raw backup',
        'Retouch photography',
        'E-invitation',
        'Reels'
      ],
      btnColor: 'bg-yellow-600 hover:bg-yellow-700',
    },
    {
      name: 'Diamond Package (Full Sensor)',
      price: 40000,
      description: '(1 day) 1 Photographer, 1 Videographer',
      features: [
        'Candid photography',
        'Portrait',
        '20 Sheets wedding album',
        'Teaser',
        'Ritual wise full video (10-20min)',
        'All Raw backup',
        'Retouch photography',
        'Interview of family and friend',
        'E-invitation',
        'Vlog & reels'
      ],
      btnColor: 'bg-blue-900 hover:bg-blue-950',
    }
  ],
  'Upanayan': [
    {
      name: 'Silver Package (Crop Sensor)',
      price: 20000,
      description: '(2 days) 1 Photographer, 1 Videographer',
      features: [
        'Candid photography',
        '20 Sheets wedding album',
        'Ritual wise full video (20-30min)',
        'All Raw backup',
        'Retouch photography',
        'E-invitation'
      ],
      btnColor: 'bg-gray-900 hover:bg-black',
    },
    {
      name: 'Gold Package (Full Sensor)',
      price: 30000,
      description: '(2 days) 1 Photographer, 1 Videographer',
      popular: true,
      features: [
        'Candid photography',
        'Portrait photography',
        '20 Sheets wedding album',
        'Teaser',
        'Ritual wise full video (30-40min)',
        'All Raw backup',
        'Retouch photography',
        'E-invitation',
        'Reels'
      ],
      btnColor: 'bg-yellow-600 hover:bg-yellow-700',
    },
    {
      name: 'Diamond Package (Full Sensor)',
      price: 80000,
      description: '(2 days) 1 Photographer, 1 Videographer',
      features: [
        'Candid photography',
        '20 Sheets wedding album',
        'Teaser',
        'Ritual wise full video (30-40min)',
        'All Raw backup',
        'Retouch photography',
        'Interview of family and friend',
        'E-invitation',
        'Vlog & reels'
      ],
      btnColor: 'bg-blue-900 hover:bg-blue-950',
    }
  ],
  'PrePostWedding': [
    {
      name: 'Silver Package (Crop Sensor)',
      price: 7000,
      description: '1 day shoot',
      features: ['1 Photographer', '1 Videographer'],
      btnColor: 'bg-gray-900 hover:bg-black',
    },
    {
      name: 'Gold Package (Full Sensor)',
      price: 10000,
      description: '1 day shoot',
      features: ['1 Photographer', '1 Videographer', '1 Assistant'],
      btnColor: 'bg-black hover:bg-gray-900',
    },
    {
      name: 'Diamond Package (Full Sensor)',
      price: 35000,
      description: '1 day shoot',
      features: ['1 Photographer', '1 Videographer', '1 Assistant'],
      btnColor: 'bg-blue-900 hover:bg-blue-950',
    }
  ],
  'ShortFilm': [
    {
      name: 'Silver Package (Crop Sensor)',
      price: 3000,
      unit: '/day',
      description: 'Short film / YouTube video',
      features: ['1 Videographer'],
      btnColor: 'bg-gray-900 hover:bg-black',
    },
    {
      name: 'Gold Package (Full Sensor)',
      price: 4500,
      unit: '/day',
      description: 'Short film / YouTube video',
      features: ['1 Videographer', '1 Assistant'],
      btnColor: 'bg-black hover:bg-gray-900',
    },
    {
      name: 'Diamond Package (Full Sensor)',
      price: 15000,
      unit: '/day',
      description: 'Short film / YouTube video',
      features: ['1 Videographer', '1 Assistant'],
      btnColor: 'bg-blue-900 hover:bg-blue-950',
    }
  ],
  'Event': [
    {
      name: 'Silver Package (Crop Sensor)',
      price: 6000,
      description: '(1 day) 1 Photographer, 1 Videographer',
      features: ['1 Photographer', '1 Videographer'],
      btnColor: 'bg-gray-900 hover:bg-black',
    },
    {
      name: 'Gold Package (Full Sensor)',
      price: 8000,
      description: '(1 day) 1 Photographer, 1 Videographer',
      features: ['1 Photographer', '1 Videographer'],
      btnColor: 'bg-black hover:bg-gray-900',
    },
    {
      name: 'Diamond Package (Full Sensor)',
      price: 30000,
      description: '(1 day) 1 Photographer, 1 Videographer',
      features: ['1 Photographer', '1 Videographer', '1 Assistant'],
      btnColor: 'bg-blue-900 hover:bg-blue-950',
    }
  ],
  'ModelShoot': [
    {
      name: 'Silver Package (Crop Sensor)',
      price: 1500,
      description: '(1 day) 1 Photographer, 1 Videographer',
      features: ['1 Photographer'],
      btnColor: 'bg-gray-900 hover:bg-black',
    },
    {
      name: 'Gold Package (Full Sensor)',
      price: 4000,
      description: '(1 day) 1 Photographer, 1 Videographer',
      features: ['1 Photographer', '1 Videographer'],
      btnColor: 'bg-black hover:bg-gray-900',
    },
    {
      name: 'Diamond Package (Full Sensor)',
      price: 20000,
      description: '(1 day) 1 Photographer, 1 Videographer',
      features: ['1 Photographer', '1 Videographer', '1 Assistant'],
      btnColor: 'bg-blue-900 hover:bg-blue-950',
    }
  ],
  'AddOn': [
    { name: 'Wedding Photographer (Crop)', price: 4000, category: 'Wedding' },
    { name: 'Wedding Videographer (Crop)', price: 4000, category: 'Wedding' },
    { name: 'Wedding Photographer (Full)', price: 6000, category: 'Wedding' },
    { name: 'Wedding Videographer (Full)', price: 6000, category: 'Wedding' },
    { name: 'Wedding Photographer (Cine)', price: 15000, category: 'Wedding' },
    { name: 'Wedding Videographer (Cine)', price: 15000, category: 'Wedding' },
    { name: 'Wedding Editor (Crop)', price: 3000, category: 'Wedding' },
    { name: 'Wedding Editor (Full)', price: 6000, category: 'Wedding' },
    { name: 'Wedding Editor (Cine)', price: 18000, category: 'Wedding' },
    { name: 'Birthday Photographer (Crop)', price: 2500, category: 'Birthday' },
    { name: 'Birthday Videographer (Crop)', price: 3000, category: 'Birthday' },
    { name: 'Birthday Photographer (Full)', price: 4500, category: 'Birthday' },
    { name: 'Birthday Videographer (Full)', price: 4500, category: 'Birthday' },
    { name: 'Birthday Editor (Crop)', price: 2000, category: 'Birthday' },
    { name: 'Birthday Editor (Full)', price: 3000, category: 'Birthday' },
    { name: 'Upanayan Photographer (Crop)', price: 3500, category: 'Upanayan' },
    { name: 'Upanayan Videographer (Crop)', price: 3500, category: 'Upanayan' },
    { name: 'Upanayan Photographer (Full)', price: 5000, category: 'Upanayan' },
    { name: 'Upanayan Videographer (Full)', price: 5000, category: 'Upanayan' },
    { name: 'Upanayan Editor (Crop)', price: 3500, category: 'Upanayan' },
    { name: 'Upanayan Editor (Full)', price: 5500, category: 'Upanayan' },
    { name: 'Event Photographer (Crop)', price: 3000, category: 'Event' },
    { name: 'Event Videographer (Crop)', price: 3000, category: 'Event' },
    { name: 'Event Photographer (Full)', price: 4000, category: 'Event' },
    { name: 'Event Videographer (Full)', price: 4000, category: 'Event' },
    { name: 'Event Editor (Crop)', price: 2000, category: 'Event' },
    { name: 'Event Editor (Full)', price: 3000, category: 'Event' },
    { name: 'Drone Mini', price: 4000, category: 'Drone' },
    { name: 'Drone Air', price: 6000, category: 'Drone' },
    { name: 'Drone Phantom', price: 7000, category: 'Drone' },
    { name: 'E-Invite Basic', price: 500, category: 'Invite' },
    { name: 'E-Invite Premium', price: 2000, category: 'Invite' },
    { name: 'Album 20 Sheets Basic', price: 4500, category: 'Album' },
    { name: 'Album 20 Sheets Standard', price: 7500, category: 'Album' },
    { name: 'Album 20 Sheets Premium', price: 12000, category: 'Album' },
    { name: 'Pendrive', price: 500, category: 'Storage' },
    { name: 'Transport cost (15-40 KM)', price: 2000, category: 'Travel' },
    { name: 'Transport cost (40-70 KM)', price: 3500, category: 'Travel' },
    { name: 'Transport cost (70-110 KM)', price: 4500, category: 'Travel' },
    { name: 'Transport cost (110-220 KM)', price: 5000, category: 'Travel' },
    { name: 'Transport cost (>220 KM)', price: 4000, category: 'Travel' },
    { name: 'Accommodation (2 Persons)', price: 2000, category: 'Stay' },
    { name: 'Extra Day Coverage', price: 5000, category: 'Service' },
    { name: 'Drone Coverage (1 Day)', price: 6000, category: 'Service' },
  ]
};
